{
 "title": "Client Details",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "hostname", "query": "raspberrypi" }
  ]
 },
 "panels": [
  { "type": "text", "gridPos": { "h": 2, "w": 22, "x": 1, "y": 0 }, "options": { "content": "# Metrics for ${hostname}\r\n" } },
  {
   "title": "Overall Client Health",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 2 },
   "targets": [
    {
     "query": "12345\r\nfrom(bucket: \"dnac\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"client\")\r\n  |> filter(fn: (r) => r[\"hostname\"] == \"${hostname}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"overall_health\")\r\n"
    }
   ]
  },
  {
   "title": "Onboarding / Connected Health",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 2 },
   "targets": [
    {
     "query": "from(bucket: \"dnac\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"client\")\r\n  |> filter(fn: (r) => r[\"hostname\"] == \"${hostname}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"onboard_health\" or r[\"_field\"] == \"connect_health\")\r\n"
    }
   ]
  },
  {
   "title": "SNR",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"dnac\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"client\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"snr\")\r\n  |> filter(fn: (r) => r[\"hostname\"] == \"${hostname}\")\r\n"
    }
   ]
  },
  {
   "title": "RSSI",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"dnac\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"client\")\r\n  |> filter(fn: (r) => r[\"hostname\"] == \"${hostname}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"rssi\")"
    }
   ]
  },
  {
   "title": "Last Connected AP",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"dnac\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"client\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"connected_ap\")\r\n    |> filter(fn: (r) => r[\"hostname\"] == \"${hostname}\")\r\n|> tail(n: 1)"
    }
   ]
  },
  {
   "title": "Last Connected SSID",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"dnac\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"client\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"connected_ssid\")\r\n    |> filter(fn: (r) => r[\"hostname\"] == \"${hostname}\")\r\n|> tail(n: 1)"
    }
   ]
  },
  {
   "title": "Frequency",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "Ghz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"dnac\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"client\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"frequency\")\r\n  |> filter(fn: (r) => r[\"hostname\"] == \"${hostname}\")\r\n  |> aggregateWindow(every: 10s, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Channel",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"dnac\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"client\")\r\n  |> filter(fn: (r) => r[\"hostname\"] == \"${hostname}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"channel\")\r\n  |> aggregateWindow(every: 1m, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Data Rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"dnac\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"client\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"dataRate\")\r\n  \r\n  |> filter(fn: (r) => r[\"hostname\"] == \"${hostname}\")\r\n  |> yield(name: \"last\")"
    }
   ]
  }
 ]
}